---
- project:
    check:
      jobs:
        - ara-tox-py3
        - ara-tox-linters
        - ara-tox-docs
        - ara-basic-ansible-devel:
            voting: false
        - ara-basic-ansible-2.9
        - ara-basic-ansible-2.8
    gate:
      jobs:
        - ara-tox-py3
        - ara-tox-linters
        - ara-tox-docs
        - ara-basic-ansible-2.9
        - ara-basic-ansible-2.8
